model:
  base_learning_rate: 4.5e-06
  target: core.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    image_key: "image"
    ddconfig:
      padding_free: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: core.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 50000
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  target: train.DataModuleFromConfig
  params:
    batch_size: 10
    train:
      target: core.data.places365.Places
      params:
        dataroot: /home/chenh/data/data_large
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'train'

